services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: flask_backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=production
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=mysql
      - DB_NAME=mydatabase
      - SECRET_KEY=mysecret
      - CORS_ALLOWED_ORIGINS=https://www.shefaug.com,https://shefaug.com,http://localhost,http://localhost:80,http://localhost:3001,http://207.154.221.54
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: vite_frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3001
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
