version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - FLASK_ENV=development
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=mysql
      - DB_NAME=mydatabase
      - SECRET_KEY=mysecret
      - CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:80,http://207.154.221.54:80,http://frontend:80,http://207.154.221.54
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: vite_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
