version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_backend
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite_frontend
    restart: always
    environment:
      - VITE_HOST=${VITE_HOST:-0.0.0.0}
      - VITE_PORT=${VITE_PORT:-3001}
    networks:
      - app_network

  nginx:
    image: nginx:1.27.5
    container_name: nginx
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
